"""add firebase_uid to users

Revision ID: 31154f54fabf
Revises: 9c2d1f6a8b3e
Create Date: 2026-07-01 14:10:32.434276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31154f54fabf'
down_revision: Union[str, None] = '9c2d1f6a8b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cooperative_groups', sa.Column('join_policy', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('firebase_uid', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_column('users', 'firebase_uid')
    op.drop_column('cooperative_groups', 'join_policy')
    # ### end Alembic commands ###
