"""add check constraint: users must have email or phone

Revision ID: 55d8f8933df5
Revises: 5ae091119ad7
Create Date: 2026-07-13 12:27:06.809209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d8f8933df5'
down_revision: Union[str, None] = '5ae091119ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_users_email_or_phone_required",
        "users",
        "email IS NOT NULL OR phone_number IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_users_email_or_phone_required", "users", type_="check")
    # ### end Alembic commands ###
