"""baseline

Revision ID: 745f0c45e4c3
Revises: 
Create Date: 2026-03-24 13:49:35.593174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '745f0c45e4c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_email'), 'feedbacks', ['email'], unique=False)
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', name='userroles'), nullable=True),
    sa.Column('crossmint_user_id', sa.String(), nullable=True),
    sa.Column('flow_address', sa.String(), nullable=True),
    sa.Column('wallet_provider', sa.String(), nullable=True),
    sa.Column('target_savings_amount', sa.Float(), nullable=True),
    sa.Column('savings_purpose', sa.String(), nullable=True),
    sa.Column('income_range', sa.Enum('below_50k', 'range_50k_100k', 'range_100k_200k', 'range_200k_350k', 'range_350k_500k', 'above_500k', name='incomerange'), nullable=True),
    sa.Column('saving_frequency', sa.Enum('daily', 'weekly', 'monthly', name='savingfrequency'), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_crossmint_user_id'), 'users', ['crossmint_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_flow_address'), 'users', ['flow_address'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_account_number'), 'bank_accounts', ['account_number'], unique=False)
    op.create_table('chat_with_ai',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cooperative_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('max_members', sa.Numeric(), nullable=False),
    sa.Column('contribution_amount', sa.Numeric(), nullable=False),
    sa.Column('contribution_frequency', sa.Enum('daily', 'weekly', 'biweekly', 'monthly', name='contributionfrequency'), nullable=False),
    sa.Column('payout_strategy', sa.Enum('rotating', 'equal', 'priority', name='payoutstrategy'), nullable=False),
    sa.Column('coop_model', sa.Enum('ajo', 'esusu', 'adashe', 'chama', 'coop', name='cooperativemodel'), nullable=False),
    sa.Column('target_amount', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'inactive', 'completed', name='cooperativestatus'), nullable=False),
    sa.Column('next_payout_date', sa.DateTime(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('chain_circle_id', sa.Integer(), nullable=True),
    sa.Column('flow_address', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('weekly_amount_usdc', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('rotation_order', sa.Enum('sequential', 'random', name='rotationorder'), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_circle_id')
    )
    op.create_index(op.f('ix_cooperative_groups_id'), 'cooperative_groups', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('info', 'success', 'warning', 'error', 'ai', 'alert', 'system', 'danger', name='notificationtype'), nullable=False),
    sa.Column('status', sa.Enum('unread', 'read', 'archived', 'deleted', name='notificationstatus'), nullable=False),
    sa.Column('event_type', sa.Enum('group', 'transaction', 'membership', 'contribution', 'payout', 'general_alert', 'system', 'ai_insight', 'other', name='eventtype'), nullable=False),
    sa.Column('entity_url', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('onchain_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_address', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('chain_id', sa.String(length=50), nullable=True),
    sa.Column('network', sa.String(length=100), nullable=True),
    sa.Column('wallet_type', sa.String(length=50), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('wallet_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onchain_wallets_wallet_address'), 'onchain_wallets', ['wallet_address'], unique=True)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stable_coin_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('local_currency', sa.Enum('NGN', 'GHS', 'KES', name='localcurrency'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('joined_group', 'left_group', 'made_contribution', 'received_payout', 'declined_invite', 'accepted_invite', 'created_group', name='activitytype'), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['cooperative_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('contribution', 'savings', 'behavior', 'group', 'milestone', 'energy_saving', 'financial_optimization', 'contribution_strategy', 'spending_analysis', 'investment_tips', 'budgeting', 'goal_setting', 'other', name='insightcategory'), nullable=False),
    sa.Column('type', sa.Enum('personal', 'group_specific', 'general', 'trending', name='insighttype'), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficultylevel'), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', 'dismissed', name='implementationstatus'), nullable=True),
    sa.Column('estimated_savings', sa.Float(), nullable=True),
    sa.Column('potential_gain', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('implementation_time', sa.Float(), nullable=True),
    sa.Column('insight_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['cooperative_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pledged', 'initiated', 'pending', 'completed', 'failed', 'cancelled', name='contributionstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cooperative_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributions_id'), 'contributions', ['id'], unique=False)
    op.create_table('group_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='membershiprole'), nullable=False),
    sa.Column('invite_code', sa.String(), nullable=True),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('clicked', 'accepted', 'pending', 'rejected', 'cancelled', name='membershipstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('payout_position', sa.Integer(), nullable=False),
    sa.Column('has_received_payout_this_cycle', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cooperative_groups.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_memberships_id'), 'group_memberships', ['id'], unique=False)
    op.create_table('wallet_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('contribution_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('deposit', 'withdrawal', 'contribution', 'refund', name='ledgertype'), nullable=False),
    sa.Column('stable_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('stable_currency', sa.Enum('usdc', 'usdt', 'cusd', 'dai', name='stablecurrency'), nullable=False),
    sa.Column('local_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('local_currency', sa.Enum('NGN', 'GHS', 'KES', name='localcurrency'), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('gateway', sa.Enum('paystack', 'flutterwave', 'cashramp', 'on_chain_cashramp', 'on_chain_solana', 'coopwise_network', 'cash', name='paymentgateway'), nullable=False),
    sa.Column('status', sa.Enum('initiated', 'pending', 'settled', 'failed', name='ledgerstatus'), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_ledger_reference'), 'wallet_ledger', ['reference'], unique=True)
    op.create_index(op.f('ix_wallet_ledger_wallet_id'), 'wallet_ledger', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_ledger_wallet_id'), table_name='wallet_ledger')
    op.drop_index(op.f('ix_wallet_ledger_reference'), table_name='wallet_ledger')
    op.drop_table('wallet_ledger')
    op.drop_index(op.f('ix_group_memberships_id'), table_name='group_memberships')
    op.drop_table('group_memberships')
    op.drop_index(op.f('ix_contributions_id'), table_name='contributions')
    op.drop_table('contributions')
    op.drop_table('ai_insights')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_onchain_wallets_wallet_address'), table_name='onchain_wallets')
    op.drop_table('onchain_wallets')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_cooperative_groups_id'), table_name='cooperative_groups')
    op.drop_table('cooperative_groups')
    op.drop_table('chat_with_ai')
    op.drop_index(op.f('ix_bank_accounts_account_number'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_flow_address'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_crossmint_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_email'), table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
