"""add_round_number_tx_id_to_contributions

Revision ID: d8b8c900456e
Revises: 6cc8f09ad76b
Create Date: 2026-03-25 08:48:34.043291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b8c900456e'
down_revision: Union[str, None] = '6cc8f09ad76b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('round_number', sa.Numeric(), nullable=True))
    op.add_column('contributions', sa.Column('tx_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributions', 'tx_id')
    op.drop_column('contributions', 'round_number')
    # ### end Alembic commands ###
