services:
  backend:
    build: ./api_backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file: .env

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: coopwise
      POSTGRES_USER: coopwise_user
      POSTGRES_PASSWORD: coopwise_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  postgres_data:
